# Generated by Django 3.2.9 on 2021-11-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonks_model_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prophetparam',
            name='score',
            field=models.FloatField(null=True, verbose_name='Оценка модели с такими параметрами'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='changepoint_prior_scale',
            field=models.FloatField(null=True, verbose_name='Параметр changepoint_prior_scale'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='changepoint_range',
            field=models.FloatField(null=True, verbose_name='Параметр changepoint_range'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='daily_seasonality',
            field=models.CharField(max_length=200, null=True, verbose_name='Параметр daily_seasonality'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='find_date',
            field=models.DateField(null=True, verbose_name='Дата подбора параметров'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='growth',
            field=models.CharField(max_length=10, null=True, verbose_name='Параметр growth'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='holidays_prior_scale',
            field=models.FloatField(null=True, verbose_name='Параметр holidays_prior_scale'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='mcmc_samples',
            field=models.IntegerField(null=True, verbose_name='Параметр mcmc_samples'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='n_changepoints',
            field=models.IntegerField(null=True, verbose_name='Параметр n_changepoints'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='seasonality_mode',
            field=models.CharField(max_length=20, null=True, verbose_name='Параметр seasonality_mode'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='seasonality_prior_scale',
            field=models.FloatField(null=True, verbose_name='Параметр seasonality_prior_scale'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='stan_backend',
            field=models.CharField(max_length=200, null=True, verbose_name='Параметр stan_backend'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='uncertainty_samples',
            field=models.IntegerField(null=True, verbose_name='Параметр uncertainty_samples'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='weekly_seasonality',
            field=models.CharField(max_length=200, null=True, verbose_name='Параметр weekly_seasonality'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='yearly_seasonality',
            field=models.CharField(max_length=200, null=True, verbose_name='Параметр yearly_seasonality'),
        ),
    ]
