# Generated by Django 3.2.9 on 2021-11-25 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stonks_model_app', '0006_auto_20211125_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prophetparam',
            name='stan_backend',
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='find_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 11, 9, 56, 217285, tzinfo=utc), verbose_name='Дата подбора параметров'),
        ),
    ]
