# Generated by Django 4.0 on 2021-12-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='ProphetParams',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('find_date', models.DateField(verbose_name='Дата подбора параметров')),
    #             ('growth', models.CharField(default='linear', max_length=10, verbose_name='Параметр growth')),
    #             ('n_changepoints', models.IntegerField(default=25, verbose_name='Параметр n_changepoints')),
    #             ('changepoint_range', models.FloatField(default=0.8, verbose_name='Параметр changepoint_range')),
    #             ('yearly_seasonality', models.CharField(default='auto', max_length=200, verbose_name='Параметр yearly_seasonality')),
    #             ('weekly_seasonality', models.CharField(default='auto', max_length=200, verbose_name='Параметр weekly_seasonality')),
    #             ('daily_seasonality', models.CharField(default='auto', max_length=200, verbose_name='Параметр daily_seasonality')),
    #             ('seasonality_mode', models.CharField(default='additive', max_length=20, verbose_name='Параметр seasonality_mode')),
    #             ('seasonality_prior_scale', models.FloatField(default=10.0, verbose_name='Параметр seasonality_prior_scale')),
    #             ('holidays_prior_scale', models.FloatField(default=10.0, verbose_name='Параметр holidays_prior_scale')),
    #             ('changepoint_prior_scale', models.FloatField(default=0.05, verbose_name='Параметр changepoint_prior_scale')),
    #             ('mcmc_samples', models.IntegerField(default=0, verbose_name='Параметр mcmc_samples')),
    #             ('interval_width', models.FloatField(default=0.8, verbose_name='Параметр interval_width')),
    #             ('uncertainty_samples', models.IntegerField(default=1000, verbose_name='Параметр uncertainty_samples')),
    #             ('score', models.FloatField(null=True, verbose_name='Оценка модели с такими параметрами')),
    #         ],
    #     ),
    # ]
