# Generated by Django 3.2.9 on 2021-12-10 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stonks_model_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prophetparams',
            name='find_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 15, 34, 0, 179627, tzinfo=utc), verbose_name='Дата подбора параметров'),
        ),
    ]
