# Generated by Django 3.2.9 on 2021-11-26 19:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stonks_model_app', '0008_auto_20211126_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 11, 26, 19, 34, 26, 301516, tzinfo=utc), verbose_name='Дата подборки')),
                ('tiker', models.CharField(max_length=10, verbose_name='Тикер')),
                ('period', models.IntegerField(verbose_name='Период прогноза')),
                ('price', models.FloatField(verbose_name='Прогнозная цена')),
                ('risk', models.FloatField(verbose_name='Риск')),
            ],
        ),
        migrations.DeleteModel(
            name='Recomendations',
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='find_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 19, 34, 26, 300530, tzinfo=utc), verbose_name='Дата подбора параметров'),
        ),
    ]
