# Generated by Django 3.2.9 on 2021-12-09 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stonks_model_app', '0009_auto_20211126_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendations',
            name='date',
        ),
        migrations.AddField(
            model_name='recommendations',
            name='date_of_recommendation',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 18, 11, 49, 302783, tzinfo=utc), verbose_name='Дата подборки'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='find_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 18, 11, 49, 301761, tzinfo=utc), verbose_name='Дата подбора параметров'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='period',
            field=models.CharField(max_length=10, verbose_name='Период прогноза'),
        ),
    ]
