# Generated by Django 4.0rc1 on 2021-12-09 18:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stonks_model_app', '0010_auto_20211209_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prophetparam',
            name='find_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 18, 14, 45, 942528, tzinfo=utc), verbose_name='Дата подбора параметров'),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='date_of_recommendation',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 9, 18, 14, 45, 943879, tzinfo=utc), verbose_name='Дата подборки'),
        ),
    ]
