# Generated by Django 4.0 on 2021-12-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonks_model_app', '0011_alter_prophetparam_find_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendations',
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='find_date',
            field=models.DateTimeField(verbose_name='Дата подбора параметров'),
        ),
    ]
