version: '3.7'

services:
  ds:
    build: web_ds
    working_dir: '/ds'
    command: python manage.py runserver 0.0.0.0:88
    volumes:
      - ./ds_api:/ds
    ports:
      - '88:88'



#    depends_on:
#      - db
#    links:
#      - 'db:postgresql'

#  db:
#    image: postgres:latest
#    env_file: .env
#    volumes:
#      - ./db:/var/lib/postgresql/data/pgdata
#    ports:
#      - "5433:5432"