# Generated by Django 3.2.9 on 2021-11-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProphetParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('find_date', models.DateField(verbose_name='Дата подбора параметров')),
                ('growth', models.CharField(max_length=10, verbose_name='Параметр growth')),
                ('n_changepoints', models.IntegerField(verbose_name='Параметр n_changepoints')),
                ('changepoint_range', models.FloatField(verbose_name='Параметр changepoint_range')),
                ('yearly_seasonality', models.CharField(max_length=200, verbose_name='Параметр yearly_seasonality')),
                ('weekly_seasonality', models.CharField(max_length=200, verbose_name='Параметр weekly_seasonality')),
                ('daily_seasonality', models.CharField(max_length=200, verbose_name='Параметр daily_seasonality')),
                ('seasonality_mode', models.CharField(max_length=20, verbose_name='Параметр seasonality_mode')),
                ('seasonality_prior_scale', models.FloatField(verbose_name='Параметр seasonality_prior_scale')),
                ('holidays_prior_scale', models.FloatField(verbose_name='Параметр holidays_prior_scale')),
                ('changepoint_prior_scale', models.FloatField(verbose_name='Параметр changepoint_prior_scale')),
                ('mcmc_samples', models.IntegerField(verbose_name='Параметр mcmc_samples')),
                ('uncertainty_samples', models.IntegerField(verbose_name='Параметр uncertainty_samples')),
                ('stan_backend', models.CharField(max_length=200, verbose_name='Параметр stan_backend')),
            ],
        ),
    ]
