# Generated by Django 3.2.9 on 2021-11-25 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stonks_model', '0003_alter_prophetparam_find_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='prophetparam',
            name='interval_width',
            field=models.FloatField(default=0.8, verbose_name='Параметр interval_width'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='changepoint_prior_scale',
            field=models.FloatField(default=0.05, verbose_name='Параметр changepoint_prior_scale'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='changepoint_range',
            field=models.FloatField(default=0.8, verbose_name='Параметр changepoint_range'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='daily_seasonality',
            field=models.CharField(default='auto', max_length=200, verbose_name='Параметр daily_seasonality'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='find_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 11, 6, 40, 763364, tzinfo=utc), verbose_name='Дата подбора параметров'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='growth',
            field=models.CharField(default='linear', max_length=10, verbose_name='Параметр growth'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='holidays_prior_scale',
            field=models.FloatField(default=10.0, verbose_name='Параметр holidays_prior_scale'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='mcmc_samples',
            field=models.IntegerField(default=0, verbose_name='Параметр mcmc_samples'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='n_changepoints',
            field=models.IntegerField(default=25, verbose_name='Параметр n_changepoints'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='seasonality_mode',
            field=models.CharField(default='additive', max_length=20, verbose_name='Параметр seasonality_mode'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='seasonality_prior_scale',
            field=models.FloatField(default=10.0, verbose_name='Параметр seasonality_prior_scale'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='stan_backend',
            field=models.CharField(default=None, max_length=200, verbose_name='Параметр stan_backend'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='uncertainty_samples',
            field=models.IntegerField(default=1000, verbose_name='Параметр uncertainty_samples'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='weekly_seasonality',
            field=models.CharField(default='auto', max_length=200, verbose_name='Параметр weekly_seasonality'),
        ),
        migrations.AlterField(
            model_name='prophetparam',
            name='yearly_seasonality',
            field=models.CharField(default='auto', max_length=200, verbose_name='Параметр yearly_seasonality'),
        ),
    ]
